# Generated by Django 4.2.7 on 2023-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0018_auto_20201015_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NurseId", models.PositiveIntegerField(null=True)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("WardId", models.PositiveIntegerField(null=True)),
                ("WardType", models.CharField(max_length=30)),
                ("NurseId", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="profile_pic",
        ),
    ]
